### ISSUE TITLE
Test suite covering basic git collaboration

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#111]
The second goal of dgit is to enable simple collaborative interactions. It will be good to build a test suite that covers typical interactions when working with a small project so that we can understand what remains, if anything, to achieve that goal. Once developed, the test suite may fail with the current implementation, but it will be useful to determine the prioritization of bugs/enhancements.

**Comment by driusan** [comment]
How would that be different than the test suite that currently exists? Most tests I created by running git on the command line, and then converting it to a go test and ensuring the output was identical.

**Comment by sirnewton01** [comment]
Yeah, maybe we can close this issue and raise other ones where we know are lacking for small project collaborations. Do you know what might be missing in terms of workflows?

I suppose I raised this as an attempt to get a handle on when we can consider the second goal of dgit "done" or not. The first appears to be done because we can handle "go get."

**Comment by driusan** [comment]
It depends how you collaborate. For a GitHub workflow, the basics are there and it's the edge cases that need to get rooted out by the git test suite (the most important things being `t1*-read-tree*.sh` which will mostly ensure that merging works, and `t2-*checkout*.sh` which will mostly ensure that checkout/branching works, which is why I was focusing on those). If you follow a `format-patch`/`am` workflow, then those commands aren't implemented at all, and if you use something than the HTTP protocol for pushing to github (or gitlab, or whatever) then the backend support isn't there yet.

Issue #10 is probably a problem for collaborations with more than 1 person or if your history isn't linear enough, but I haven't looked into it yet because it's a pain to get a setup to reproduce it and develop at the same time.

**Comment by sirnewton01** [comment]
Thanks, I'll raise some more issues on these areas and tag them for a "basic collaboration" release.

**Comment by sirnewton01** [comment]
I'm closing this issue as it doesn't really have anything directly actionable.
