### ISSUE TITLE
Switch to using a logging package instead of Printf's

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#28]
There are some fmt.Printf's in the code base that provide some debugging information. If we switch to using a logging package the logging level can be adjusted at runtime without have to recompile removing/adding Printf's.

**Comment by sirnewton01** [comment]
The built-in log package is probably sufficient for this project's needs.

**Comment by driusan** [comment]
The main reason I haven't used the built-in log package is because of the timestamp that it adds by default, making it harder to get the exact same output as real git which just prints error message to stderr when things go wrong. (I assume there's a way to customize the timestamp, but I haven't looked into it.)

**Comment by sirnewton01** [comment]
Perhaps we could use the golang logging for debugging and tracing level information and Printf for expected messages and errors? This would allow us to turn the debugging and tracing on/off at runtime and still match standard git. What do you think?

**Comment by driusan** [comment]
That sounds like a pretty solid plan someone wants to do it, but it sounds like a lot of work to get it set up that I don't have the time to do personally. The only thing I'd suggest changing is checking a DGIT_TRACE variable which supercedes GIT_TRACE, so that git and dgit tracing levels can be set independently.

**Comment by sirnewton01** [comment]
I have implemented this in Pull Request #37

**Comment by driusan** [comment]
Merger
