### ISSUE TITLE
Is the cmd package intended to be used as a library?

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#73]
The cmd package has a number of exported functions, which could lead a third-party implementor to use them directly as function calls. Is this the intent or just a side-effect of the package structure (ie. callable from main.go in the parent package)?

**Comment by sirnewton01** [comment]
If the cmd package is not intended to be callable as a library then perhaps we could pull that package up into the top-level package and un-export most of the functions. This would make it more clear to implementors that they should be using the git package, otherwise, integrate by invoking the dgit binary using the contract specified in the official git manual pages.

**Comment by driusan** [comment]
I've thought about this and come to the conclusion that I don't really care. On the one hand, it would be nice if `cmd` could be used as a library so that people could easily write alternative interfaces (and I've thought of making a `package main` in a directory named `git` which is hidden behind a Plan9-only build flag, but I'm not doing that any time soon), on the other hand, I don't think anyone's likely to use the package for that anyways and now that it calls `os.Exit` in a few places, it's probably not wise to use the package as a library. 

They're mostly in a different package/exported so that they can be called as "cmd.Foo" in main. I'm fine with either leaving it, moving them up to the package main, or moving the entire thing down to a `package main` in `cmd/dgit`to have a slightly more idiomatic layout. I don't have any strong opinions on this.

**Comment by sirnewton01** [comment]
My current thinking is leaning more towards pulling the cmd/* up into the root along with main and make it a package main. I'm just not sure what would be good timing for this.

**Comment by sirnewton01** [comment]
I wonder if 9fans might be a good place for dgit?

**Comment by driusan** [comment]
I think we can close this issue for now, the question is answered and we seem to be fine with the way things are being handled.
